# Generated by Django 4.2.1 on 2023-06-25 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Checkin date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='Checkout date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
